### ISSUE TITLE
Avoiding Hardcoded WiFi credentials.

### ISSUE THREAD

**Issue by teamsdiot** [Team-SDIoT/EazyExit#15]
Hardcoding WiFi credentials(SSID and PASSWORD) is not a good idea, Keeping in mind change of House routers and wanting to connect to different Access point, password changes. We need a dynamic way to handle seamless WiFI connection on the go.

**Comment by iayanpahwa** [comment]
Assigning it to myself.

**Comment by iayanpahwa** [comment]
@embtux @anshulkatta PR generated, can you guys please review and merge it!

PR: #16 <https://github.com/Team-SDIoT/EazyExit/pull/16>

**Comment by iayanpahwa** [comment]
PR merged!
