### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by embtux** [Team-SDIoT/EazyExit#2]
Add complete build description for the project.

- Host OS.
- Package dependencies (if any)
- Toolchain name with version and URL.
- Build Instructions.

**Comment by embtux** [comment]
Recommended build host - Ubuntu-16.04 (LTS).

**Comment by iayanpahwa** [comment]
@embtux PR generated #13 . Can you please review and merge the changes.

**Comment by iayanpahwa** [comment]
PR #13 merged! Closing the issue.
