### ISSUE TITLE
Setup ON and OFF String as system wide for communicating for switch on and off

### ISSUE THREAD

**Issue by anshulkatta** [Team-SDIoT/EazyExit#28]
The Server side will send ASCII value in CAPS - "ON" and  "OFF" , the client should be able to handle this as CAPS value in check or ignoreCase check

**Comment by iayanpahwa** [comment]
@git-akshay please take a look at this issue and resolve the issue by changing mitt_publish strings to "ON" and "OFF" respectively.

**Comment by git-akshay** [comment]
Acknowledged.

**Comment by iayanpahwa** [comment]
@git-akshay PING. Please close this one asap!

**Comment by iayanpahwa** [comment]
PR #33 Merged! Closing this issue!
