### ISSUE TITLE
segregate firmwares for diff boards under /firmware directory.

### ISSUE THREAD

**Issue by teamsdiot** [Team-SDIoT/EazyExit#7]
We're planning to use different Microcontrollers/SoCs and WLAN modules for this project, hence it's better to segregate all the firmware files in a generic /firmware directory in root folder of this project, 
Hence replacing firmware_ESP8266 ----> firmware/ESP8266.ino and etc.

**Comment by iayanpahwa** [comment]
@git-akshay please start working on this issue.

**Comment by git-akshay** [comment]
@iayanpahwa PR generated #9 https://github.com/Team-SDIoT/EazyExit/pull/9.
Please review and merge.

**Comment by iayanpahwa** [comment]
@git-akshay PR merged, closing the issue!
